### PR TITLE
feat: implement "clicking" on events with keyboard (#636)

### PR DESCRIPTION
**Pull request by klao**
## Checklist

Please put "X" in the below checkboxes that apply:

- [ ] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [x] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [ ] If committing a new feature, I have also written the appropriate tests for it. 
- [x] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

**Premium**
- [ ] I'm a Schedule-X premium user

## This PR solves the following problem**. 

See #636.

I don't quite know how to create tests for this change. I tested manually with all kind of events in all kind of views.

## How to test this PR**. 

1. Create a calendar with full-day and normal events and different views.
2. Add the event modal plugin or add some logging in `callbacks.onEventClick`. (Or both, as these are different mechanisms!)
3. Navigate by pressing Tab repeatedly to an event. Press Space or Enter.
4. Observe the modal to pop up and the callback being called.

### CODE REVIEW

**Comment by klao** [comment]
Note that I changed the order of `setClickedEvent` and `invokeOnEventClickCallback` in the month-agenda-event. This is for consistency with all the other places, where they are invoked from different event handlers. But `onMouseUp` always happens before the `onClick` if both are present.

**Review by tomosterlund — APPROVED** [review]

**Comment by tomosterlund** [comment]
> Note that I changed the order of `setClickedEvent` and `invokeOnEventClickCallback` in the month-agenda-event. This is for consistency with all the other places, where they are invoked from different event handlers. But `onMouseUp` always happens before the `onClick` if both are present.

nice catch!

**Comment by tomosterlund** [comment]
Thanks a lot for this feature too!

I added an issue and linked it to this one, because it would be a nice feature to follow this one. So if you have a moment and want to add even more accessibility, feel free to grab it, otherwise I'll surely get to it later too

**Comment by klao** [comment]
Thank you! I will take a look later.

**Pull request merged**
