### PR TITLE
fix #722: strip all-day events of time in ical plugin so they are represented accurately in views

### LINKED ISSUE #722: All day events from ICS show up as spanning an extra day beyond the range end
**Context:**

See reproduction

**Describe the bug**

All day events show up as spanning an extra day beyond the range end.

**To Reproduce**

You can open up  [this repository](https://github.com/justin-hackin/schedule-x-ics-allday-repro) in stackblitz to see the issue. The ics string is an unadulterated export from a google calendar.

**Expected behavior**

The single day all day event shows up as spanning 1 day, not 2.

### PR DESCRIPTION
**Pull request by justin-hackin**
## Checklist

Please put "X" in the below checkboxes that apply:

- [ X ] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [ X ] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [ ] If committing a new feature, I have also written the appropriate tests for it. 
- [ X ] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

**Premium**
- [ ] I'm a Schedule-X premium user

## This PR solves the following problem**. 

See issue #722 

## How to test this PR**. 

You can check out the fork of this repo and use the `test-example` branch of it to see the fix.

NOTE: the scheduleX representation of all day events differs from ical representation. In ical both start/end time are at midnight and for a one day all-day event, the end day is on the _next_ day.

### CODE REVIEW

**Review by tomosterlund — COMMENTED** [review]
Works great for me. A test case for an all-day event in the ics string would be cool too. Are you familiar with vitest/jest already, or would you prefer I add it?

**Comment by tomosterlund** [comment]
@justin-hackin could you please toggle that maintainers can commit? I tried pushing a couple of tests but permission was denied

**Comment by justin-hackin** [comment]
> @justin-hackin could you please toggle that maintainers can commit? I tried pushing a couple of tests but permission was denied

Screenshot 2024-10-19 at 1 49 30 PM

It seems like that's the default permission. I will take it out of draft and see what happens. Sorry for the delay, I'm going to set up GH notifications again.

**Comment by tomosterlund** [comment]
Ah, thanks! Now I managed to push :)

**Comment by tomosterlund** [comment]
Thanks for contributing!

Will make a new release asap, when I'm back from my vacation in a couple of weeks, just didn't want to roll out a new latest version while out of office.

**Comment by justin-hackin** [comment]
> Thanks for contributing!
> 
> Will make a new release asap, when I'm back from my vacation in a couple of weeks, just didn't want to roll out a new latest version just before being out of office.

Okay, that's good to know. Sorry this PR was so hasty 🤦‍♂️ and thanks for noticing and fixing the obvious mistake I made 😮‍💨

Hope you have a great vacation and thanks for playing it safe!

**Pull request merged**
