### PR TITLE
Config time units

### LINKED ISSUE #666: Custom TimeUnits implementation
**Is your feature request related to a problem? Please describe.**  
I want a way to customize calendar, in order to use the calendar with the [Jewish calendar](https://www.chabad.org/library/article_cdo/aid/526875/jewish/The-Jewish-Calendar-Year.htm)*

*) In short, a lunar calendar, but with an extra month added in some years (according to a fixed system) to keep the months more or less in sync with the seasons of the year (AKA, the solar calendar)

**Describe the solution you'd like**  
It looks like using a custom TimeUnits implementation would be enough; that should keep the months starting and ending according the Jewish  month instead of the gregarorion, for example.

Could an option be added to `CalendarConfig` to specify the TimeUnits implementation? That should allow schedule-x to support any calendar system, without adding any complexity.

**Additional context**  

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [x] I believe I know how to do this, and am willing to implement the whole thing.

### PR DESCRIPTION
**Pull request by yringler**
## Checklist

Please put "X" in the below checkboxes that apply:

- [ ] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [ x ] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [ ] If committing a new feature, I have also written the appropriate tests for it. 
- [ x ] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

**Premium**
- [ ] I'm a Schedule-X premium user

## This PR solves the following problem**. 

Fixes #666

## How to test this PR**. 

For example:  
1. Feed X and Y in the events-Prop. 
2. Click Z or A. 
3. Confirm that B is displayed.

### CODE REVIEW

**Comment by yringler** [comment]
@tomosterlund , this ended up being a bigger PR than I had hoped, and it doesn't seem to work.
IDK if I'll have time to work on this further; any tips, or think maybe it's something you might finish off?

**Comment by tomosterlund** [comment]
Did you also try overriding `$app.timeUnitsImpl` with another implementation of the same interface?

That might save us a lot of code changes compared to now.

I currently also don't have time to work on this, but if you want we can just leave it open for now, and then I can continue at some later point when I have the time for it

**Comment by yringler** [comment]
Right, I started in that direction, but I had passed in the timeunitsimpl via the config, and then I discovered the internal config, and it kind of spiraled out from there.
Now I have a better idea of how config works (like, the internal vs external, signals and builders etc).
If I get to this again, I'll probably still pass it into the external config, but not move it over to the internal config.

It would be nice if the calendar could reactively change between implementations - maybe if $app exposed timeunitsimpl as a signal (with a getter to get the `.value` to minimize code churn)? Then it would update if the config object changed?

This was my first time working with preact/signals, I'm a bit fuzzy on parts.

> I currently also don't have time to work on this, but if you want we can just leave it open for now, and then I can continue at some later point when I have the time for it

Sounds good! I guess we'll see who continues on it first. The race is on 🏎️

**Comment by yringler** [comment]
[Here's a demo I put together](https://github.com/yringler/my-schedule-x-demo/blob/master/src/jewish-calendar-time-impl.ts), with a jewish calendar impl. Not 100% if it works, though - I didn't get as far as adding unit tests to it.

**Comment by tomosterlund** [comment]
Unfortunately I don't see driving myself this one home anytime soon. There's just too many requests for me to focus on this.

I'd gladly review it though, if you'd find the time to finish this feature.

**Pull request closed without merging**
