### PR TITLE
feat: Improve pointer movement during DnD

### PR DESCRIPTION
**Pull request by harry-73**
## Checklist

Please put "X" in the below checkboxes that apply:

- [ ] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [X] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [X] If committing a new feature, I have also written the appropriate tests for it. 
- [X] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

**Premium**
- [ ] I'm a Schedule-X premium user

## This PR solves the following problem**. 

See issue #735 

If the PR is accepted, refactorings should be done.

### CODE REVIEW

**Comment by tomosterlund** [comment]
It's a cool idea, but the way it is now the time displayed doesn't update while dragging. I think we do need to update the time of the copy whenever the position changed.

So maybe a combination of this approach + continuing to update the copy while moving, or did that not work for you?

**Comment by harry-73** [comment]
In my case, I do not care as I think mainly users are focused more on the placement than looking at the time but I will look how to update the time of copy while dragging.

**Comment by harry-73** [comment]
The issue is that I use translate to do the vertical movement. If I use`this.updateCopy(this.eventCopy)`  to update the time displayed in the copy, the placement is also modified and it is a little chaotic.
Need to think a bit more.

**Comment by tomosterlund** [comment]
I'd be open to a PR again, if it improves the pointer position without causing any breaking changes

**Pull request closed without merging**
