### PR TITLE
feat(calendar): Annual view agenda mode

### PR DESCRIPTION
**Pull request by dovepa**
Hello team,

🎉 This is my first contribution to the project (schedule-x). I’ve opened a PR to introduce a new annual view for the calendar.

This new view provides a comprehensive overview of all planned events throughout the year. By clicking the "see more events" button, the calendar will automatically switch to the monthly view.

 Currently, I haven't figured out how to manage recurrence or enable drag-and-drop for events in this mode yet.

 I'd love to hear your thoughts on this addition and any suggestions you might have. Do you think this feature could be integrated into the project?

Thank you for your consideration!

Best regards,
Dove

image

### CODE REVIEW

**Comment by tomosterlund** [comment]
Hey 👋  thanks for opening this. Looks like a bigger one, but I'll try and have a look later this week

**Comment by dovepa** [comment]
Thank you :)  By the way, I didn't notice it earlier, but I fixed a bug regarding the number of visible months.

Here is the correct result:

image

**Comment by tomosterlund** [comment]
Now I had a chance to have a little look on this. First of all, great job! I like the idea, especially for use cases where there are not so many events in each month, like maybe for birthday calendars.

However, I still aim to implement a year view for Schedule-X, modeled after the Google-calendar year view. Something like in the following image, but with little colored dots under the dates with events, just like in the month agenda view.

Bildschirmfoto 2024-06-29 um 10 32 38

I would be open to PRs for a view like that, but if the view you have built in this PR is something you would like to release, you could also release it via npm from your fork, and then I'd love to add it in a "community" section in the docs.

**Comment by dovepa** [comment]
Thank you! I'm glad you like the idea. Could you please explain how I can publish the view separately on npm?

**Pull request closed without merging**
